In [ ]:
from google.colab import files

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
x=files.upload()

Saving Dataset (1).xlsx to Dataset (1).xlsx

In [ ]:
dealer=pd.read_excel('Dataset (1).xlsx',sheet_name='Dealers')

In [ ]:
dealer.head()

   Dealer_ID      Dealer_Name Dealer_Country      State       City  ZIpCode
0          1  Kenneth Schmitt          india        Goa      Panji   400001
1          2  Owen Mclaughlin          india      Delhi     Naoida   400002
2          3  Donald Repinski          india  Karnataka  Bangalore   400003
3          4    Rachel Oszust          india     Gujrat  Ahemdabad   400004
4          5       Lynn Knapp          india     Orrisa    Cuttack   400005

In [ ]:
df_customers=pd.read_excel('Dataset (1).xlsx',sheet_name='Customers')

In [ ]:
df_claims=pd.read_excel('Dataset (1).xlsx',sheet_name='Claims')

In [ ]:
df_parts=pd.read_excel('Dataset (1).xlsx',sheet_name='Parts')

In [ ]:
df_transactions=pd.read_excel('Dataset (1).xlsx',sheet_name='Transactions')

In [ ]:
df_vendors=pd.read_excel('Dataset (1).xlsx',sheet_name='Vendors')

In [ ]:
df_claims['Dealer_ID'].value_counts().head(10)

5       971
3       922
2       922
1       922
6       394
4       218
1248    176
1256    176
1255    176
1254    176
Name: Dealer_ID, dtype: int64

In [ ]:
df_claims['Part_ID'].value_counts().head(10)

906    4019
901    3349
905    3349
907    3348
902    2010
903    2010
904    2010
Name: Part_ID, dtype: int64

In [ ]:
df_claims['Repair_or_Replace'].value_counts().head(10)

rplc    14736
rpr      5359
Name: Repair_or_Replace, dtype: int64

In [ ]:
df_claims.head().head()

,claim_id,claim_date,claim_amount,Dealer_ID,Cust_ID,Part_ID,Repair_or_Replace
0,1,2020-04-01,36000,5,104,901,rpr
1,2,2020-04-01,42000,6,106,902,rplc
2,3,2020-04-01,45000,4,103,903,rpr
3,4,2020-04-01,56000,3,102,904,rplc
4,5,2020-04-01,39000,2,105,905,rpr

In [ ]:
df_claims

,claim_id,claim_date,claim_amount,Dealer_ID,Cust_ID,Part_ID,Repair_or_Replace
0,1,2020-04-01,36000,5,104,901,rpr
1,2,2020-04-01,42000,6,106,902,rplc
2,3,2020-04-01,45000,4,103,903,rpr
3,4,2020-04-01,56000,3,102,904,rplc
4,5,2020-04-01,39000,2,105,905,rpr
...,...,...,...,...,...,...,...
20090,20091,2021-01-24,53000,1274,43974,906,rplc
20091,20092,2021-01-24,36000,1275,43975,907,rplc
20092,20093,2021-01-24,46000,1276,43976,905,rplc
20093,20094,2021-01-24,56000,1277,43977,904,rplc
20094,20095,2021-01-24,33000,1278,43978,902,rpr

In [ ]:
rpr_or_rplc=pd.get_dummies(df_claims['Repair_or_Replace'],drop_first=True)

In [ ]:
rpr_or_rplc

       rpr
0        1
1        0
2        1
3        0
4        1
...    ...
20090    0
20091    0
20092    0
20093    0
20094    1

[20095 rows x 1 columns]

In [ ]:
df_claims

,claim_id,claim_date,claim_amount,Dealer_ID,Cust_ID,Part_ID,Repair_or_Replace
0,1,2020-04-01,36000,5,104,901,rpr
1,2,2020-04-01,42000,6,106,902,rplc
2,3,2020-04-01,45000,4,103,903,rpr
3,4,2020-04-01,56000,3,102,904,rplc
4,5,2020-04-01,39000,2,105,905,rpr
...,...,...,...,...,...,...,...
20090,20091,2021-01-24,53000,1274,43974,906,rplc
20091,20092,2021-01-24,36000,1275,43975,907,rplc
20092,20093,2021-01-24,46000,1276,43976,905,rplc
20093,20094,2021-01-24,56000,1277,43977,904,rplc
20094,20095,2021-01-24,33000,1278,43978,902,rpr

In [ ]:
df_claims.drop(['Repair_or_Replace'],axis=1,inplace=True)

In [ ]:
df_claims=pd.concat([df_claims,rpr_or_rplc],axis=1)

In [ ]:
df_claims

       claim_id claim_date  claim_amount  Dealer_ID  Cust_ID  Part_ID  rpr
0             1 2020-04-01         36000          5      104      901    1
1             2 2020-04-01         42000          6      106      902    0
2             3 2020-04-01         45000          4      103      903    1
3             4 2020-04-01         56000          3      102      904    0
4             5 2020-04-01         39000          2      105      905    1
...         ...        ...           ...        ...      ...      ...  ...
20090     20091 2021-01-24         53000       1274    43974      906    0
20091     20092 2021-01-24         36000       1275    43975      907    0
20092     20093 2021-01-24         46000       1276    43976      905    0
20093     20094 2021-01-24         56000       1277    43977      904    0
20094     20095 2021-01-24         33000       1278    43978      902    1

[20095 rows x 7 columns]

In [ ]:
df_claims.columns=['claim_id','claim_date','claim_amount','Dealer_ID','Cust_ID','Part_ID','Target']

In [ ]:
df_claims

       claim_id claim_date  claim_amount  Dealer_ID  Cust_ID  Part_ID  Target
0             1 2020-04-01         36000          5      104      901       1
1             2 2020-04-01         42000          6      106      902       0
2             3 2020-04-01         45000          4      103      903       1
3             4 2020-04-01         56000          3      102      904       0
4             5 2020-04-01         39000          2      105      905       1
...         ...        ...           ...        ...      ...      ...     ...
20090     20091 2021-01-24         53000       1274    43974      906       0
20091     20092 2021-01-24         36000       1275    43975      907       0
20092     20093 2021-01-24         46000       1276    43976      905       0
20093     20094 2021-01-24         56000       1277    43977      904       0
20094     20095 2021-01-24         33000       1278    43978      902       1

[20095 rows x 7 columns]

In [ ]:
df_claims.drop(['claim_id','claim_date','Dealer_ID','Cust_ID'],axis=1,inplace=True)

In [ ]:
df_claims

       claim_amount  Part_ID  Target
0             36000      901       1
1             42000      902       0
2             45000      903       1
3             56000      904       0
4             39000      905       1
...             ...      ...     ...
20090         53000      906       0
20091         36000      907       0
20092         46000      905       0
20093         56000      904       0
20094         33000      902       1

[20095 rows x 3 columns]

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(df_claims.drop('Target',axis=1),df_claims['Target'],test_size=0.20,random_state=60)

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
dc=DecisionTreeClassifier()

In [ ]:
dc.fit(x_train,y_train)

DecisionTreeClassifier()

In [ ]:
y_pred=dc.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
print(accuracy_score(y_test,y_pred))

1.0

In [ ]:
from sklearn.model_selection import cross_val_score

In [ ]:
dc=DecisionTreeClassifier()
cross_val_score(dc,df_claims.drop('Target',axis=1),df_claims['Target'],cv=10,scoring='accuracy').mean()

1.0

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
lr=LogisticRegression()
cross_val_score(lr,df_claims.drop('Target',axis=1),df_claims['Target'],cv=10,scoring='accuracy').mean()

0.7000248880039821

In [ ]:
from sklearn.linear_model import LogisticRegression
logmo=LogisticRegression()
logmo.fit(x_train,y_train)
log_pred=logmo.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [ ]:
print(accuracy_score(y_test,y_pred)*100)

100.0

In [ ]:
print(confusion_matrix(y_pred,y_test))

[[2979    0]
 [   0 1040]]